### ISSUE TITLE
debug接口500

### ISSUE THREAD

**Issue by kingswjw** [phalapi/phalapi#102]
sys.debug=true或URL添加参数__debug__=1，接口500

**Comment by phalapi** [comment]
可以贴下详细的报错信息吗？谢谢

**Comment by kingswjw** [comment]
Request URL: http://localhost/phalapi/public/?s=App.Hello.World&__debug__=1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Oct 2019 05:08:42 GMT
Server: Apache/2.4.34 (Unix) PHP/7.1.23
X-Powered-By: PHP/7.1.23
s: App.Hello.World
__debug__: 1

**Comment by kingswjw** [comment]
> 可以贴下详细的报错信息吗？谢谢

Request URL: http://localhost/phalapi/public/?s=App.Hello.World&__debug__=1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Oct 2019 05:08:42 GMT
Server: Apache/2.4.34 (Unix) PHP/7.1.23
X-Powered-By: PHP/7.1.23
s: App.Hello.World
__debug__: 1

**Comment by kingswjw** [comment]
> 可以贴下详细的报错信息吗？谢谢

Request URL: http://localhost/phalapi/public/?s=App.Hello.World&__debug__=1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Oct 2019 05:08:42 GMT
Server: Apache/2.4.34 (Unix) PHP/7.1.23
X-Powered-By: PHP/7.1.23
s: App.Hello.World
__debug__: 1

**Comment by phalapi** [comment]
这是正常的，请见 2.8.0 版本说明：http://docs.phalapi.net/#/v2.0/changelog

```
1、文件日志PhalApi\Logger\FileLogger区分隐式静默和显式异常两种模式，可通过\PhalApi\DI()->debug全局模式或初始化时指定调试模式。为调试模式时，若写入失败将500异常提示
```

**Comment by phalapi** [comment]
日志目录缺少写入权限，为runtime添加777权限就可以了。500是因为本地也关了错误提示。
