### ISSUE TITLE
可以贴下详细的报错信息吗？谢谢

### ISSUE THREAD

**Issue by kingswjw** [phalapi/phalapi#103]
可以贴下详细的报错信息吗？谢谢

Request URL: http://localhost/phalapi/public/?s=App.Hello.World&__debug__=1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Oct 2019 05:08:42 GMT
Server: Apache/2.4.34 (Unix) PHP/7.1.23
X-Powered-By: PHP/7.1.23
s: App.Hello.World
__debug__: 1

**Comment by kingswjw** [comment]
phalapi 2.7.0 版本测试正常

**Comment by phalapi** [comment]
https://github.com/phalapi/kernal/releases/tag/2.9.1

2.9.1版本会优化修复，谢谢。
