### ISSUE TITLE
diDefautl是不是拼错了

### ISSUE THREAD

**Issue by jiangslee** [phalapi/phalapi#106]
https://github.com/phalapi/phalapi/blob/0acfe0867fa991688d5ec6514cb6c86dbdb7e98a/vendor/phalapi/kernal/src/Request/Parser.php#L78

diDefautl是不是拼错了，感觉diDefault才对。。

**Comment by phalapi** [comment]
源代码看得好细致！kernal中此局部变量名称已修正。
