### ISSUE TITLE
https访问docs文档含有http链接的不安全问题

### ISSUE THREAD

**Issue by gaoweifan** [phalapi/phalapi#107]
当我访问在线接口列表的时候，浏览器会提示此页面包含其他不安全的资源，希望将所有http链接诸如"http://cdn7.phalapi.net/20180316214150_f6f390e686d0397f1f1d6a66320864d6"、"http://docs.phalapi.net/#/v2.0/"、"http://www.phalapi.net/"、"http://pro.phalapi.net/"替换为https链接

**Comment by phalapi** [comment]
好的，将优化处理

**Comment by phalapi** [comment]
已处理
