### ISSUE TITLE
new \NotORM_Literal ( "NOW()" )报错

### ISSUE THREAD

**Issue by mousesmalltail** [phalapi/phalapi#110]
你好请问大师为什么我这句话 
new \NotORM_Literal ( "NOW()" )
 写在model里的class里面就没错，但是写在demain的calss里面就报错
![image](https://user-images.githubusercontent.com/49893345/78138430-75790c00-7459-11ea-82b9-849fc840c2cf.png)
我应该在demain的类里面怎么写才不会报错？

**Comment by phalapi** [comment]
温馨提示：在2.x版本中，当需要使用NotORM_Literal类进行加１操作时，须注意两点：需要先获取NotORM实例再创建NotORM_Literal对象；注意命名空间，即要在最前面加反斜杠。   

参见：  
http://docs.phalapi.net/#/v2.0/database-usage
