### ISSUE TITLE
规则验证require和min先后问题

### ISSUE THREAD

**Issue by HOBERHUNTER** [phalapi/phalapi#113]
'page' => array('name' => 'page', 'type' => 'int', 'min' => 1, 'require' => false, 'default' => 1, 'desc' => '分页'),

分页参数是可选，但是配置了min，没有传递该参数则报错，
正常逻辑是否应为require为true之后在判断min
这个算是bug？
版本：2.12.2

**Comment by HOBERHUNTER** [comment]
修正下，排查后是'default' => =-1, 'min' => 1问题，这个情况下参数可选会出错

**Comment by phalapi** [comment]
这是规则逻辑错误，如果需要要求参数最小值为1，却配置了默认值为-1，是不合理的。可以去掉 默认配置或默认值为1
