### ISSUE TITLE
我想写一个phalapi-swoole-extends来将phalapi整合即时通讯且框架常驻内存

### ISSUE THREAD

**Issue by peter6968** [phalapi/phalapi#117]
想问下哪些需要特别注意的，如phalApi_DI::$instance等一些静态变量或者其他的一些问题
如果已经有类似的扩展包，请推荐给我，就不用写了>_<

**Comment by phalapi** [comment]
暂时没有类似的扩展包，官方期待你的分享！

**Comment by peter6968** [comment]
我碰到了框架整合中关于DI() static instance与$_GET , $_REQUEST , $_POST , $_FILES在phalapi内部的实现，我该怎样才能从第三方包的角度解决这些问题？

**Comment by phalapi** [comment]
可以试下重载后改写

**Comment by peter6968** [comment]
好的，我放弃了对静态变量，全局变量的修改，新建新的访问入口避开使用\PhalApi\PhalApi()来避免这些问题
PS：针对phalapi 1.x

**Comment by fywtat** [comment]
针对swoole肯定是重构版了。

**Comment by peter6968** [comment]
世上无难事，只要肯放弃！
