### ISSUE TITLE
PhalApi 的 GPL许可协议，对商业程序不友好啊🙈🙈🙈

### ISSUE THREAD

**Issue by liyujiang-gzu** [phalapi/phalapi#118]
基于GPL许可协议开发的程序，传说必须同样使用GPL协议开放Source Code，不能作为闭源的，连作为Object Code引用都不行。LGPL协议才允许不开源，可作为Object Code引用。

**Comment by phalapi** [comment]
感谢提醒，已从GPL调整为Apache开源协议。

**Comment by liyujiang-gzu** [comment]
> 感谢提醒，已从GPL调整为Apache开源协议。

和官网的中文版授权协议也不太一样：https://www.phalapi.net/license.html

**Comment by phalapi** [comment]
https://www.phalapi.net/license.html
官网开源协议已同步更新。
