### ISSUE TITLE
到处都是 substr(PHP_SAPI, 0, 3) == 'cli' 判断不友好

### ISSUE THREAD

**Issue by huye** [phalapi/phalapi#120]
在以 php 的 cli-server 模式开发测试时，全都判定为 cli 命令行运行了，这是一个问题。
还有就是象 swoole 这样的本来就是 cli 模式的服务，更是全都不能用了。

希望能另外定义一个常量，以这个常量来保存是否 cli 模式的状态。

**Comment by phalapi** [comment]
这样的判断是不合理，但应该出现的次数不多
