### ISSUE TITLE
2.x版本自带的User好像有问题

### ISSUE THREAD

**Issue by cxelove** [phalapi/phalapi#121]
user是在插件里面初始化$di->user = new \App\Common\User\User();
而这个时候API里面获取参数列表还没有完成，也就在User的__construct构造函数里无法获得user_id和token等参数，这导致islogin总是false

**Comment by phalapi** [comment]
DI的注册位置和顺序可以调整下，或调整成延时注册，或者在完成过滤器操作后重新初始化。
自带的User扩展后续再继续完善。

**Comment by adamgogogo** [comment]
是token不对, $_REQUEST 和 $_POST 的token不一样，$_POST 的token才是数据库的token。
