### ISSUE TITLE
多个过滤器共同协作

### ISSUE THREAD

**Issue by nckf** [phalapi/phalapi#122]
这两天学习 PhalAPI ,在实现多个过滤器上遇到的问题.
从文档上看,过滤器的添加方式如下:
`$di->filter = new App\Common\UserFilter();` 
而当我想实现多个过滤器的时候我的想法是:
`$di->filter = array('user'=> $di->filter = new App\Common\UserFilter());`
显然这是行不通的.
是否我还能从其他方面入手?或者重构过滤器的加载方法

**Comment by phalapi** [comment]
多个过滤器，可以重载实现过滤器，再在自己的过滤中进行调度，执行自己的多个过滤器。
