### ISSUE TITLE
源码中需要保留哪些版权信息？

### ISSUE THREAD

**Issue by Coolkkmeat** [phalapi/phalapi#123]
因为想开源整个项目，后端是依靠PhalApi的，看了看网站下面“许可”写的是：“页面上的产品名称以及指向官网的连接还有源代码中关于PhalApi的版权信息及作者信息必须保留”。
请问是指哪些源代码、页面？
比如：是否包括config下文件里的内容？composer.json里的内容？

**Comment by phalapi** [comment]
PhalApi PHP源代码中类注释的源作者信息保留即可。页面上的版本信息可相应调整，但需要在衍生开源项目中注明是使用PhalApi即可。
