### ISSUE TITLE
?s=App.User_User.CheckSession

### ISSUE THREAD

**Issue by pycamel** [phalapi/phalapi#128]
"
\nFatal error:  Uncaught Error: Call to a member function isLogin() on null in /usr/local/nginx/html/phalapi/src/app/Api/User/User.php:103\nStack trace:\n#0 [internal function]: App\\Api\\User\\User->checkSession()\n#1 /usr/local/nginx/html/phalapi/vendor/phalapi/kernal/src/PhalApi.php(53): call_user_func(Array)\n#2 /usr/local/nginx/html/phalapi/public/index.php(9): PhalApi\\PhalApi->response()\n#3 {main}\n  thrown in /usr/local/nginx/html/phalapi/src/app/Api/User/User.php on line 103
\n"

这个接口一直报500错误，但是看官方示例没问题。

**Comment by pycamel** [comment]
附上解决方法：
/Api/User/User.php
添加
use App\Domain\User\UserSession as UserSessionDomain;

然后在原来检测登陆状态处替换

public function checkSession()
    {
        $Common = new UserSessionCommon();
        $user = \PhalApi\DI()->user;
        $is_login = $Common->isLogin();
        return array('is_login' => $is_login);
    }

**Comment by phalapi** [comment]
这是因为，user是一个内置的插件，高版本才发布的。

di注册代码位置在：
https://github.com/phalapi/phalapi/blob/master-2x/plugins/phalapi_user.php

同时，如果需要启动插件，还需要修改 https://github.com/phalapi/phalapi/blob/master-2x/config/di.php

把以下代码注释去掉：
```php
// 加载plugins目录下的第三方应用初始化文件
// foreach (glob(API_ROOT . DIRECTORY_SEPARATOR . 'plugins' . DIRECTORY_SEPARATOR . '*.php') as $pluginFile) {
//    include_once $pluginFile;
// }
```
