### ISSUE TITLE
用dblib连接sqlserver失败

### ISSUE THREAD

**Issue by deerlou** [phalapi/phalapi#130]
用dblib连接sqlserver时好像有点小问题 ，NotORMDatabase里有支持dblib的方法，但是在343行缺少了dblib_sqlserver的条件，不能成功连接数据库，添加上就能成功使用，不知道直接添加会不会有其他影响

**Comment by phalapi** [comment]
官方默认是推荐使用 PDO的方式连接sqlserver，需要用到pdo_sqlsrv扩展。可参考数据库的连接文档：http://docs.phalapi.net/#/v2.0/database-connect。如果使用dblib方式连接，欢迎提供343行的修改代码，我们来更新下。
