### ISSUE TITLE
phalapi使用postgresql时lastInsertId不能正常获取ID值

### ISSUE THREAD

**Issue by github-yyg** [phalapi/phalapi#2]
PhalApi/NotORM/NotORM/Result.php中 
方法:
function insert_id(){
        return $this->notORM->connection->lastInsertId();
    }
返回最后插入行的ID，或者是一个序列对象最后的值，取决于底层的驱动。比如，PDO_PGSQL() 要求为 name 参数指定序列对象的名称.。未传入序列对象的名称导致该问题的发生。

**Comment by phalapi** [comment]
非常感谢反馈！但由于我们对pgsql或者其他类似的数据库经验不足，可否提供解决方案？以便我们更新上去，下次发布，再次感谢！

**Comment by phalapi** [comment]
补充，这个问题之前已有同学反馈，并且后面又有新的反馈，已更新到master，提交纪录请见：https://github.com/phalapi/phalapi/commit/93fded4c61c604c36f19cee95b7825bbd52055e9  
  
具体的内容请参考：http://git.oschina.net/dogstar/PhalApi/commit/93fded4c61c604c36f19cee95b7825bbd52055e9  
  
谢谢！
