### ISSUE TITLE
可否添加一个“是否在不匹配时显示正则内容”的开关？

### ISSUE THREAD

**Issue by RexSkz** [phalapi/phalapi#21]
假设 getRules 中的正则如下：

```php
'regex' => "/^([0-9A-Za-z\\-_\\.]+)@([0-9a-z]+\\.[a-z]{2,3}(\\.[a-z]{2})?)$/i",
```

我故意输入一个：`email=asd`，然后会提示：

```
非法请求：email无法匹配/^([0-9A-Za-z\\-_\\.]+)@([0-9a-z]+\\.[a-z]{2,3}(\\.[a-z]{2})?)$/i
```

一般来说，这样的提示不应该只在开发环境下才会有的么？**生产环境暴露正则的具体内容，可能会导致正则被绕过，从而引发安全问题。**

这个提示是 StringFormatter#filterByRegex 发出来的，我没有在里面找到关闭它的方法。

**Comment by phalapi** [comment]
已使用调试模式```DI()->debug``` 作为控制开关，提交请见 ：https://github.com/phalapi/phalapi/commit/616f6c1650346cc2ef4145f9f5884245fdc54ff5

**Comment by RexSkz** [comment]
好的，期待新版本~
