### ISSUE TITLE
安卓开发使用Retrofit2 post,请求Phalapi的接口，后台获取不到数据！

### ISSUE THREAD

**Issue by pythonsir** [phalapi/phalapi#27]

**Comment by phalapi** [comment]
可否提供一下，请求的接口链接是？  

获取不到，具体是指？比如，接口返回的状态码是什么，头部信息是什么。如果能把报文信息贴一下更好。

**Comment by JavaBird** [comment]
![image](https://user-images.githubusercontent.com/5122200/31649094-d77680be-b2d6-11e7-82cb-13c2ae1f2e55.png)
![image](https://user-images.githubusercontent.com/5122200/31649108-e31416d4-b2d6-11e7-98bb-bbffee2c854e.png)
![image](https://user-images.githubusercontent.com/5122200/31649133-fd8a0064-b2d6-11e7-9a5d-4158fdaa03f0.png)

**Comment by JavaBird** [comment]
通过post请求，最后都重定向301

**Comment by JavaBird** [comment]
这是通过GET请求的，数据可以获取到。
![image](https://user-images.githubusercontent.com/5122200/31649266-9c20a372-b2d7-11e7-8911-510bd8fbbdde.png)
![image](https://user-images.githubusercontent.com/5122200/31649276-ad396072-b2d7-11e7-98f1-cbe411eb99ce.png)
目前几乎所有从安卓发出的post请求，都访问不到，只有get的请求可以访问到。

**Comment by phalapi** [comment]
怀疑是服务器部署有问题。框架本身没有限制POST就进行301跳转，但如果设置了参数的source为POST时，会要求此参数须通过POST方式传递而已。

**Comment by JavaBird** [comment]
在Public/project 下面新建一个php类，$_POST是可以获取到数据的。

**Comment by phalapi** [comment]
参考此示例：http://demo.phalapi.net/checkApiParams.php?service=Default.Index

在线调试，是使用POST方式的。访问下你本地，测试下行不行。另外，你本地的服务器是nginx，还是apache，还是其他？
