### ISSUE TITLE
日志或配置文件目录若缺少写入权限，则不能写入日记和进行文件缓存以及接下配置无法生效

### ISSUE THREAD

**Issue by lzyroot** [phalapi/phalapi#3]
chmod 777都试过了还是提示这个。。。

**Comment by phalapi** [comment]
这只是作为提示信息，不影响安装创建。可关注最后的符号是打勾还是打叉，这里若打叉则会有影响。  
  
另外，除了使用可视化安装，也可以使用命令：```phalapi-buildapp```进行快速创建。可参考：[创建一个自己的项目](https://www.phalapi.net/wikis/%5B1.2%5D-%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E8%87%AA%E5%B7%B1%E7%9A%84%E9%A1%B9%E7%9B%AE.html)  
  
再次感谢你的使用与反馈！
