### ISSUE TITLE
请问如何接受处理对象数组。

### ISSUE THREAD

**Issue by chin3651** [phalapi/phalapi#30]
如 array = [
{
id:1,
name:'a'
},
{
id:2,
name:'b'
}
]

**Comment by phalapi** [comment]
可以使用array类型的参数，然后设置为JSON格式，示例：  
```
array('name' => '{你的参数名字}', 'type' => 'array', 'format' => 'json')
```

然后在客户端以JSON格式传递，在接口就可以收到一个数组。文档请参考：https://www.phalapi.net/wikis/1-12.html
