### ISSUE TITLE
用 PhalApi\Request 获取header参数有BUG

### ISSUE THREAD

**Issue by chenwengen** [phalapi/phalapi#34]
环境：windows+php5.6.27+NGINX1.11.5
用 PhalApi\Request 获取header参数有BUG、Postman header 发送参数key为headparam 用request类的getHeader方法获取参数 $request->getHeader('headparam')返回为空！
`经过断点发现getallheaders()函数返回的数组key为Headparam首字母变大写了！[](url)`
可以用array_change_key_case( getallheaders()) 返回！

**Comment by phalapi** [comment]
通常情况下，header的名称都是以大写字母开头的，所以PhalApi也遵循这一约定。可以通过传入开头为大写的参数获取相应的头部信息。  

例如当前页面的响应头部：  
```
Vary:X-PJAX,Accept
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:deny
X-GitHub-Request-Id:544C:2BF50:409D5:62D5E:5A2FD0DC
X-Request-Id:4f0ec0288271143c068916809009d5cb
X-Runtime:0.531760
X-Runtime-rack:0.538022
X-UA-Compatible:IE=Edge,chrome=1
X-XSS-Protection:1; mode=block
```

**Comment by Jason-cqtan** [comment]
版本：2.17.2
问题：参考http://docs.phalapi.net/#/v2.0/api-params?id=%e5%85%ac%e5%85%b1%e5%8f%82%e6%95%b0%e9%85%8d%e7%bd%ae%e9%80%89%e9%a1%b9
设置参数规则为header方式传递
```php
'apiCommonRules' => [
    'rid'  => [
                'name' => 'rid',
                'require' => true,
                'type' => 'string',
                'source' => 'header',
                'default' => 'default',
                'desc' => '请求流水号',//请求流水号（header参数）
                'on_after_parse' => 'trim|strtolower'
       ]
]
```
key为rid，始终使用了默认值`default`，未使用传递值，自己调试可在./vendor/phalapi/kernal/src/Request.php 217行左右添加`$data = array_change_key_case($data,CASE_LOWER);` 将获取的到的值统一转小写可解决。
望作者更新下
