### ISSUE TITLE
关于配置多个数据库

### ISSUE THREAD

**Issue by RockXiong** [phalapi/phalapi#38]
我在框架中配置了两个数据库dba和dbc，两个数据库里有表名称一样的表tb_a，请问我在操作这个表的时候怎么指定是操作哪个数据库中的tb_a?

**Comment by phalapi** [comment]
可以配置多份数据库配./config/dbs.php，然后根据需要在Model层使用对应的配置。例如：  
![qq 20180107155228](https://user-images.githubusercontent.com/12585518/34647654-c95d5c46-f3c2-11e7-9f89-f42d24ad4b38.jpg)
