### ISSUE TITLE
SDK(PHP)中超时设置无效

### ISSUE THREAD

**Issue by heihusdm** [phalapi/phalapi#4]
SDK/PHP/PhalApiClient/PhalApiClient.php文件中定义的超时设置为
`protected $timeoutMs`
![image](https://cloud.githubusercontent.com/assets/2971707/24234088/7fb4ec1a-0fd1-11e7-93c2-299c7c1f2334.png)

而在超时设置方法里(withTimeout)却是
`$this->timeoutMS = $timeoutMS`
![image](https://cloud.githubusercontent.com/assets/2971707/24234101/882383fc-0fd1-11e7-879b-506ba9b14eeb.png)

  也就是timeoutMs在两处大小写不一致，而在发起接口请求方法request中调用doRequest时是使用
`$this->timeoutMs`
如下：
`$rs = $this->doRequest($url, $this->params, $this->timeoutMs);
此时
`$this->timeoutMs`
的值仍然为空，从而导致超时设置无效

@dogstar

**Comment by phalapi** [comment]
感谢反馈！如邮件沟通，已在[master修复](https://github.com/phalapi/phalapi/commit/afaf196031bc1f3fc000937234f6dc5894cfee17)，下个版本会更新。
