### ISSUE TITLE
关闭&__debug__的debug信息

### ISSUE THREAD

**Issue by tuntron** [phalapi/phalapi#41]
看了文档，上面显示增加&__debug__可以显示debug信息，那岂不是任何人都可以这样查看接口的debug信息吗？
找了半天没看到关闭这个debug的操作。

**Comment by tuntron** [comment]
![image](https://user-images.githubusercontent.com/6416166/36639481-96bf3a50-1a48-11e8-8c75-7d058009525f.png)
竟然在这里。。。好吧，麻烦文档也说明一下，不然刚接触的时候有点懵逼！

**Comment by phalapi** [comment]
文档上有说明的，请见[接口响应与在线调试 - 在线调试](http://docs.phalapi.net/#/v2.0/response-and-debug?id=%e5%9c%a8%e7%ba%bf%e8%b0%83%e8%af%95)    

开启调试模式很简单，主要有两种方式：

 +  单次请求开启调试：默认添加请求参数&__debug__=1
  + 全部请求开启调试：把配置文件./Config/sys.php文件中的配置改成'debug' => true,

**Comment by phalapi** [comment]
补充，1.x 文档也有更详细的说明，https://www.phalapi.net/wikis/2-13.html：  

```
2.13.1 开启调试调试

开启调试模式很简单，主要有两种方式：

    单次请求开启调试：默认添加请求参数&__debug__=1
    全部请求开启调试：把配置文件./Config/sys.php文件中的配置改成'debug' => true,

请特别注意，在实际项目中，调试参数不应使用默认的调试参数，而应各自定义，使用更复杂的参数，从而减少暴露敏感或者调试信息的风险。例如：

    不推荐的做法：&__debug__=1
    一般的做法：&__phalapi_debug__=1
    更好的做法：&__phalapi_debug__=202cb962ac59075b964b07152d234b70
```
