### ISSUE TITLE
Response返回data，200为对象，其他为数组

### ISSUE THREAD

**Issue by Jackfinal** [phalapi/phalapi#42]
Response返回data，200为对象，其他（400，401等）为数组
这样会造成app端 json解析有问题，
查看源代码发现，data默认为array,而返回400的时候没有对data进行赋值

`{
    "ret": 200,
    "data": {
        "title": "Hello PhalApi",
        "version": "2.2.0",
        "time": 1519691269
    },
    "msg": "",
}`

`{
    "ret": 400,
    "data": [],
    "msg": "非法请求：用户不存在."
}`

建议在PhalApi类中，第54行增加 
`$rs->setMsg((object)[]);`
对默认值的类型进行修改.

**Comment by phalapi** [comment]
感谢反馈，这个问题之前已经发现。  

未作调整，是考虑到这是底层很通用的返回，如果改动，可能会对以往的客户端有影响，并且会涉及大量的文档同步更新。所以，框架层面暂时先不调整。  

解决方案：在项目级别可以调整，重新继承Request类，并当data为空数组时，切换到object即可。

**Comment by phalapi** [comment]
再补充下，在项目可这样扩展调整：   

1、先添加一个新类，在src/app/Common/Response.php 文件，放置下面代码  
```
<?php

namespace App\Common;

class MyResponse extends \PhalApi\Response\JsonResponse  {

	public function getResult() {
		$rs = parent::getResult();

		// 将空数组转换成空对象
		if (empty($rs['data']) && is_array($rs['data'])) {
			$rs['data'] = (object)$rs['data'];
		}

		return $rs;
	}
}
```

2、然后，修改./config/di.php，重新注册response服务，在最后一行添加：  
```
$di->response = new \App\Common\MyResponse();
```

**Comment by Jackfinal** [comment]
看到，感谢 这个方法很好，自定义
