### ISSUE TITLE
怎么 新建在src/下新建一个home

### ISSUE THREAD

**Issue by baomanxi** [phalapi/phalapi#44]
怎么 新建在src/下新建一个home,文档没有描述。

**Comment by phalapi** [comment]
[如何增加一个顶级命名空间？](http://docs.phalapi.net/#/v2.0/autoload?id=%e5%a6%82%e4%bd%95%e5%a2%9e%e5%8a%a0%e4%b8%80%e4%b8%aa%e9%a1%b6%e7%ba%a7%e5%91%bd%e5%90%8d%e7%a9%ba%e9%97%b4%ef%bc%9f)
