### ISSUE TITLE
建议3.x的时候把vendor挪掉。可以参考下laravel对于依赖的做法

### ISSUE THREAD

**Issue by xiaohuilam** [phalapi/phalapi#46]
如果 vendor被添加到版本库，那么就鼓励开发去修改vendor。
这有违开源社区的模式。

**Comment by phalapi** [comment]
感谢建议，但考虑到国内同学对于composer的了解不多，为照顾大部分新手，特意将vendor放到phalapi这个外壳项目中，方便开箱即用（甚至不需要安装composer），降低学习成本。  

而对于composer有经验的同学，自然也会知道，可以把vendor在git中排除。简单改下gitignore配置即可。  

例如我们的[Kernal核心项目](https://github.com/phalapi/kernal)就没有把vendor放到git，因为它是一个内核项目。接触它的目标人群至少是专业的开发了。
