### ISSUE TITLE
phal2.2.2 insert数据之后返回的主键id 是 0

### ISSUE THREAD

**Issue by soapper** [phalapi/phalapi#47]
主键不是自增生成的，是自己计算的

**Comment by phalapi** [comment]
如果是这样，那就需要用自己的方式来取新的ID吧

**Comment by soapper** [comment]
@phalapi 发现了，原来是因为只能返回自增的id。。。复杂的curd操作只能在model里不是很方便，这是出于什么考虑？

**Comment by phalapi** [comment]
一时较难说清，具体可参考官方文档。
