### ISSUE TITLE
为什么不用composer

### ISSUE THREAD

**Issue by aoswce** [phalapi/phalapi#5]
为什么不用composer 做依赖管理？
也没有命名 空间....

**Comment by phalapi** [comment]
PhalApi最初是没有考虑使用命名空间的，是为了避免像JAVA那重复编写累赘的命名空间。但正在研发的 PhalApi 2.0 项目会采用命名空间和composer。请见：http://git.oschina.net/dogstar/PhalApi/issues/66

**Comment by phalapi** [comment]
@aoswce 现在2.x版本已经完美支持composer，感谢关注。
