### ISSUE TITLE
文档里面有一个手误

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#51]
http://docs.phalapi.net/#/v2.0/model?id=%e6%95%b0%e6%8d%ae%e5%ba%93%e8%a1%a8%e5%90%8d%e9%85%8d%e7%bd%ae
下图红框(看样子应该也是我和一样打五笔的)
![image](https://user-images.githubusercontent.com/628011/38590193-43842d2c-3d62-11e8-9f4a-9fd88d187f11.png)

**Comment by phalapi** [comment]
谢谢反馈，已修复。
