### ISSUE TITLE
关于Soap扩展

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#52]
刚接触PhalApi几天，这就是我想要的，足够简单并且易于扩展，感谢！

使用过程中由于需要提供WebService功能，查了一下发现以前的soap扩展是针对旧版的，
所以就学习了一下修改了一个版本。

https://github.com/chenall/phalapi-soap

有需要的可以安装使用

```
composer require chenall/phalapi-soap
```

PS： 第一次写composer扩展，自己测试使用正常。

**Comment by phalapi** [comment]
赞！感谢分享，已更新到官网：http://docs.phalapi.net/#/v2.0/library
