### ISSUE TITLE
关于多数据库访问

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#56]
我有一组服务器A,B,C,D数据库结构完全一样.

我有时需要访问服务器A的,有时需要访问的是服务器B的.

除了为每个服务器的数据库建不同名的MODEL,有没有什么更好的方法? 

我目前是使用同一个MODEL,但在使用之前先判断当前要访问的是哪个数据库,预先修改默认服务器指向.

但是这样子无法同时调取两个服务器的数据.

**Comment by phalapi** [comment]
使用两份dbs.php配置，注册两个notorm实例，按需要切换使用即可。

**Comment by chenall** [comment]
抱歉,我不是很理解.
能不能给个使用的例子?谢谢!

**Comment by phalapi** [comment]
复制一份dbs.php配置为dbs2.php后： 
```
./config/dbs.php
./config/dbs2.php
```

在./config/di.php文件中，注册多一个notorm实例，新的实例使用dbs2配置：  
```
// 数据操作 - 基于NotORM
$di->notorm = new NotORMDatabase($di->config->get('dbs'), $di->debug);

// 再注册一个，使用新配置
$di->notorm2 = new NotORMDatabase($di->config->get('dbs2'), $di->debug);
```

最后，在Model层，创建一个Model基类MyModelBase，重载\PhalApi\Model\NotORMModel::getORM()方法，改用新注册的notorm2：

```
class MyModelBase extends \PhalApi\Model\NotORMModel {
    protected function getORM($id = NULL) {
        $table = $this->getTableName($id);
        return \PhalApi\DI()->notorm2->$table; // 改成notorm2
    }
}
```

后面如果需要第二个数据库的，就让Model子类继续这个MyModelBase即可。

**Comment by chenall** [comment]
明白了,谢谢! 主要就是重载getORM,一时没有反应过来.
