### ISSUE TITLE
app发送的post请求参数接收不到

### ISSUE THREAD

**Issue by dangpengsong** [phalapi/phalapi#59]
同事用app发送postpost请求，这边参数接收不到，但是我自己写html或者用curl或浏览器插件这些都可以拿到参数，是不是app（安卓和ios）发送的post请求不标准还是类型不一样，拿不到参数？

**Comment by phalapi** [comment]
应该是android发送的问题。可以：  
1、抓一下安卓发的包，看下发送的参数是什么   
2、在服务端，在index.php一开始，就把 $_POST 打印出来看下

**Comment by dangpengsong** [comment]
用php://input可以接受到数据，是同事发的的POST请求不标准，不能被识别，已解决，谢谢

**Comment by pluveto** [comment]
你要确保两个事情, 第一:

 headers: {
        'Content-Type': 'application/x-www-form-urlencoded', //
    }

头部类型必须如此

第二:

var loginBody = qs.stringify({
        email: "i@pluvet.com",
        nonce: nonce,
        sign: sha1(xxx),
    });

请求正文放在请求体(Body), 并且进行了字符串化. 不要发成json(除非专门为此设计过).

**Comment by ZhenZinian** [comment]
请问是不是phalapi不支持接收Json格式的请求，貌似现在大部分app给后台都是传递json啊，为啥没支持捏

**Comment by phalapi** [comment]
> 请问是不是phalapi不支持接收Json格式的请求，貌似现在大部分app给后台都是传递json啊，为啥没支持捏

可参考下：关于无法接收application/json数据 ，http://talk.phalapi.net/?/question/368
