### ISSUE TITLE
官方文档可以改进一下下

### ISSUE THREAD

**Issue by ihewro** [phalapi/phalapi#6]
有些路径字母一下子大写一下子小写

建议统一一下下

非常感谢该项目

**Comment by phalapi** [comment]
外部可访问的路径目录，即Public内的是全部小写路径。其他目录则是首写字母大写。  
  
具体要改进的地方，可否给几个示例？以便我们改进，谢谢！

**Comment by ihewro** [comment]
路径比如下图：

![20170422204946](https://cloud.githubusercontent.com/assets/20165605/25304602/4fa9a468-2730-11e7-89d3-479c72d7be05.png)

```
http://localhost/phalapi/public/myapp/
```
正确应该是：
```
http://localhost/Phalapi/Public/myapp/
```

应该是笔误吧

官网文档，字体太大了，而且旁边木有目录树，翻看起来很不方便。

可以尝试使用markdown写，这样写起来比较简单，条目比较清晰

可以尝试使用https://github.com/QingWei-Li/docsify 工具构建文档

只是一些些个人看法O(∩_∩)O哈！

**Comment by phalapi** [comment]
感谢反馈！public相关的地方已调整。  
  
文档是用markdown编写的，然后再生成 HTML 更新到官网。请见：  http://git.oschina.net/dogstar/PhalApi/wikis/home  

docsify这个工具我先看下，也可以参考下这里带有目录的在线文档： http://wiki.phalapi.net/

**Comment by ihewro** [comment]
奥！搜嘎， http://wiki.phalapi.net/ 这个看着舒服多辣！
