### ISSUE TITLE
关于请求参数规则(意见)

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#60]
使用这个框架有一段时间了,目前有一个小问题,就是关于参数规则的.

个人觉得目前的参数规则的编写方式应该还有改进的余地,我的考虑主要有两点(主要还是懒^_^)

1.  复用(可能好几个API里面有参数都是一样的).
2.  编辑器友好(API参数传递给D之后我希望在D里面可以有代码提示,知道有哪些参数)

当然了这些只有个人的想法,不知有没有人愿意去实现?

**Comment by phalapi** [comment]
比较中肯的建议。  

1、可以使用apiCommonRules配置重复的参数规则，请见[应用参数](http://docs.phalapi.net/#/v2.0/api?id=%e5%ba%94%e7%94%a8%e5%8f%82%e6%95%b0)，或者使用DI全局容器注册通用的参数，然后在配置时使用：\PhalApi\DI()->which_rule。  
2、期待有同学来实现分享！
