### ISSUE TITLE
issue #22 的白名单问题文档中没有写

### ISSUE THREAD

**Issue by finntenzor** [phalapi/phalapi#65]
文档中 1.5 中的 应用参数并没有提及“白名单”的问题，但是框架代码中对“白名单”做了处理（将require改为false），并且默认设定了白名单（Site.Index）。
但是这样文档不写清楚很容易让人误解，建议将这个问题写到1.5的应用参数中。

**Comment by phalapi** [comment]
1.5的应用参数，是指？

**Comment by finntenzor** [comment]
以下页面：
http://docs.phalapi.net/#/v2.0/api?id=%E5%BA%94%E7%94%A8%E5%8F%82%E6%95%B0 

仅仅说明了“应用参数”是对全部接口生效的，但是没有说明白名单配置，也没有给相关链接，造成初学者会看到“部分配置失效”的假象。

建议将“白名单配置”（ http://docs.phalapi.net/#/v2.0/filter?id=%E7%99%BD%E5%90%8D%E5%8D%95%E9%85%8D%E7%BD%AE ）作为相关链接放到“应用参数”附近，以方便初学者。

**Comment by phalapi** [comment]
谢谢提醒，已补充到 [多个参数规则时的优先级](http://docs.phalapi.net/#/v2.0/api?id=%e5%a4%9a%e4%b8%aa%e5%8f%82%e6%95%b0%e8%a7%84%e5%88%99%e6%97%b6%e7%9a%84%e4%bc%98%e5%85%88%e7%ba%a7)
