### ISSUE TITLE
修改返回空数组[]，为返回空对象{}

### ISSUE THREAD

**Issue by zynfly** [phalapi/phalapi#67]
https://github.com/phalapi/phalapi/blob/8cdc1d903712535ee7bb075ca44d87eee98e3e4b/vendor/phalapi/kernal/src/Response.php#L165

很多序列化框架不支持把空数组解析成空对象。

如下是修改建议

    public function getResult()
    {
        $rs = array(
            'ret' => $this->ret,
            'data' => empty($this->data) ? new \stdClass() : $this->data,
            'msg' => $this->msg,
        );

        if (!empty($this->debug)) {
            $rs['debug'] = $this->debug;
        }

        return $rs;
    }

**Comment by phalapi** [comment]
下个版本更新此优化，https://github.com/phalapi/kernal/commit/ea6f36271e87a0a02acdd965090297f32867643d
