### ISSUE TITLE
关于notorm的一个修改建议

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#68]
目前notorm只有query的用法(所有的操作最终都是执行query)

建议增加exec用法
用途:  创建临时表,执行一些特殊的命令等.

因为query是经过prepare这后执行的,像mssql如果通过query创建临时表是无效的
我目前是使用如下方式.

```
$this->getORM()->getConn()->exec($sql);
```

**Comment by phalapi** [comment]
好建议，有空帮忙完善一下，然后提个PR？谢谢！
