### ISSUE TITLE
关于同服务器多个API站点的部署

### ISSUE THREAD

**Issue by chenall** [phalapi/phalapi#69]
在同一个服务器上需要部署多个站点，各个API之间还需要可以互相调用，大家都是如何做的？

有没有什么比较好的建议？

**Comment by wccplatform** [comment]
目录结构大概这样：

├── LICENSE
├── README.md
├── bin
│   ├── build_sqls.php
│   ├── build_test.php
│   ├── cli
│   ├── phalapi-buildsqls
│   └── phalapi-buildtest
├── composer.json
├── composer.lock
├── config
│   ├── alpha.php
│   ├── app.php
│   ├── beta.php
│   ├── dbs.php
│   ├── di.php
│   ├── e.php
│   ├── production.php
│   └── sys.php
├── data
│   └── phalapi.sql
├── language
│   ├── de
│   ├── en
│   ├── fr
│   ├── zh_cn
│   └── zh_tw
├── public
│   ├── docs.php
│   ├── examples
│   ├── exclude.conf
│   ├── favicon.ico
│   ├── index.php
│   └── init.php
├── runtime
│   └── log
├── sdk
│   ├── C_Sharp
│   ├── Go
│   ├── JAVA
│   ├── JS
│   ├── Objective-C
│   ├── PHP
│   ├── Python
│   ├── React-Native
│   └── Ruby
**
├── src
│   ├── api
│   └── app
**
├── tests
│   ├── app
│   ├── bootstrap.php
│   ├── map.php
│   └── phpunit.xml
└── vendor
    ├── autoload.php
    ├── beberlei
    ├── bin
    ├── composer
    ├── paragonie
    ├── phalapi
    ├── phpmailer
    ├── symfony

1. 在composr.json  里面增加
```json
psr-4": {
            "App\\": "src/app",
            "Api\\": "src/api"
}
```

2. compose update 

这样src 下的 api 和app 就各自是一个站点了，除了api层，domain层model层可以在两个站点间相互调用
