### ISSUE TITLE
当服务不存在时不是应该向客户端传递HTTP状态码吗?

### ISSUE THREAD

**Issue by pluveto** [phalapi/phalapi#87]
如题

vendor\phalapi\kernal\src\ApiFactory.php

        if (!class_exists($apiClass)) {
            http_response_code(404);
            throw new BadRequestException(
                T('no such service as {service}', array('service' => $service)),
                4
            );
        }

**Comment by phalapi** [comment]
是可以的。各有各的设计，如果用HTTP状态码，就要考虑到客户端和使用方。因为除了浏览器，还可能是App，又或是python、lua、php脚本之类。为了方便统一处理，所以采用了都是HTTP 200返回，但通过json结果来告知。

有需要，可以在reponse或入口处，根据需要调整。
