### ISSUE TITLE
配置多个数据库时候, 调用get、update时会提示 dbs.tables should not be empty

### ISSUE THREAD

**Issue by swatyb123** [phalapi/phalapi#97]
https://github.com/phalapi/phalapi/blob/51069e6e0d7a35bfdfde1d248fdb98878d819ac2/vendor/phalapi/kernal/src/Model/NotORMModel.php#L140

**Comment by phalapi** [comment]
已修复优化，修改纪录：https://github.com/phalapi/kernal/commit/d9987540b7f1ce305633d08243a1381b49248a66  

将会在下个版本进行更新。

**Comment by swatyb123** [comment]
好的
